Add CI workflow for the project
mcruzdev/platformoon-web pull request #5
Opened 2023-10-04 02:57 UTC by Amnish04

Hi @mcruzdev,
I just added a `ci` workflow that checks for linting errors, builds the application, and runs the test script (commented out for now as there are no tests).

Please review my changes, and let me know if something needs to be changed before it the PR can be merged.

This fixes #2

2023-10-04 09:33 UTC, mcruzdev requested changes

2023-10-04 09:33 UTC, mcruzdev commented on .github/workflows/ci.yml
> +    # No tests yet
I think that we can remove this comment, I will create an issue to add tests, TY!

2023-10-04 13:13 UTC, Amnish04 commented on .github/workflows/ci.yml
> +    # No tests yet
Just removed tests from ci pipeline as requested

2023-10-04 13:14 UTC, Amnish04 commented on .github/workflows/ci.yml
> +    # No tests yet
Just removed tests from ci pipeline as requested

2023-10-05 13:29 UTC, mcruzdev commented
Thank you @Amnish04!

2023-10-05 13:29 UTC, merged